name: vsynth
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - sdv
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - sdv
      - torch
      - torchvision
      - torchaudio
